name: ci

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.6-spark-2.4.7
          build-args: |
            PYTHON_VERSION=3.6
            SPARK_VERSION=2.4.7
            OPENJDK_VERSION=8
            PY4J_VERSION=0.10.7
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}