name: ci-docker-build-and-push

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - python-3.6-spark-2.4.7
        id: python-36-spark-247
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.6-spark-2.4.7
          build-args: |
            PYTHON_VERSION=3.6
            SPARK_VERSION=2.4.7
            OPENJDK_VERSION=8
            PY4J_VERSION=0.10.7
      -
        name: Build and push - python-3.7-spark-2.4.7
        id: python-37-spark-247
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.7-spark-2.4.7
          build-args: |
            PYTHON_VERSION=3.7
            SPARK_VERSION=2.4.7
            OPENJDK_VERSION=8
            PY4J_VERSION=0.10.7
      -
        name: Build and push - python-3.7-spark-3.0.1-openjdk-8
        id: python-37-spark-301-openjdk-8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.7-spark-3.0.1-openjdk-8
          build-args: |
            PYTHON_VERSION=3.7
            SPARK_VERSION=3.0.1
            OPENJDK_VERSION=8
            PY4J_VERSION=0.10.9
      -
        name: Build and push - python-3.7-spark-3.0.1
        id: python-37-spark-301
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.7-spark-3.0.1
          build-args: |
            PYTHON_VERSION=3.7
            SPARK_VERSION=3.0.1
            PENJDK_VERSION=11
            PY4J_VERSION=0.10.9
      -
        name: Build and push - python-3.8-spark-3.0.1-openjdk-8
        id: python-38-spark-301-openjdk-8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.8-spark-3.0.1-openjdk-8
          build-args: |
            PYTHON_VERSION=3.8
            SPARK_VERSION=3.0.1
            PENJDK_VERSION=8
            PY4J_VERSION=0.10.9
      -
        name: Build and push - python-3.8-spark-3.0.1
        id: python-38-spark-301
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark:python-3.8-spark-3.0.1
          build-args: |
            PYTHON_VERSION=3.8
            SPARK_VERSION=3.0.1
            PENJDK_VERSION=11
            PY4J_VERSION=0.10.9
      -
        name: Build and push - latest
        id: latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jaygovind/pyspark
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jaygovind/pyspark
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}